### PR TITLE
renamed EventProtocol to CaseAccessible

### PR DESCRIPTION
**Pull request by gringoireDM**
Quite often it's useful to access an enum associated value without a switch statement, or an if to use pattern matching. Still, the name `EventProtocol` makes hard to be used in a different context like a state. 
`EventProtocol` is now a type alias for `CaseAccessible`. In an event context `EventProtocol` should be used, while if using this feature in a different context, `CaseAccessible` should be used.

`CaseAccessible` also add updatability for enum, particularly useful for more functional state patterns.

### CODE REVIEW

**Comment by classic-chris** [comment]
I don't think adding the ability to update the associated value of an enum case is a good idea. I have looked through the conversation on the Swift forum but the arguments for this change are not entirely convincing. Furthermore, allowing for a change of state like this is not in the spirit of a functional style of programming.

I would argue against including this functionality in MERLin as I do not believe it adds value or encourages best practices.

**Comment by gringoireDM** [comment]
I agree for what concerns our use cases, but pure functional programming has the idea that you just have functions and transformations. technically you should not have a var or a let. With this in mind, the update function would serve the purist of functional programming like who asked in the swift evolution thread for this feature as indispensable for the proposal to fill the gap with structs. 

Note that enum are closer to structs than classes. They are on the stack and an update of the payload for an enum case will in fact cause the creation of a new enum case instance having the updated value. This is quite useful in the proper context. 

```swift
enum State: CaseAccessible {
   case count(Int)
   case error
}

enum Action: CaseAccessible {
    case increment(Int)
    case decrement(Int)
}

let action: Observable<Action> = ...

Observable.marge( 
    action.capture(event: Action.increment),
    action.capture(event: Action.decrement) .map { -$0 }
).scan(into: State.count(0)) { $0[case: Stat.count, default: 0] += $1 }
```

This is a stupid example.

Personally I don't like it. But I'm not 100% functional. MERLin is not just for us. it's intended to serve a broader community, hopefully and if this can be useful in swift programming language I'm sure it can serve well more advanced functional patterns in MERLin too.

**Comment by classic-chris** [comment]
I really question the value of this functionality and the original comparison to structs. While structs and enums have some technical similarities they are clearly not the same thing and have quite different use cases (something you pointed out as well).

Stepping back from what Swift may or may not eventually adopt, I'm struggling to see the value of this feature and why it should be included in MERLin. MERLin's focus is on events which should always be uniquely generated rather than mutated after creation.

I'm trying to think of a use-case where mutating the associated value of the case is preferable to returning a new case with a different associated value.

**Comment by gringoireDM** [comment]
Chris, updating a value and returning a new one with updated value is exactly the same thing.
doing `state[case: State.count] = 2` is exactly the same as
```swift
var state: State = ...
if case .count = state {
    state = State.count(2)
}
```

and `state[case: State.count, default: 0] += 1` is exactly the same as
```swift
var state: State = ...
if case let .count(value) = state {
    state = .count(value + 1)
}
```
The difference is that syntactically is cleaner and saves more than few lines of code.
With stream of events, this remains unfeasible, because events passed around in Rx streams are `let` therefore cannot be changed. the mutating update function can't be used in MERLin streams. 
Different story is for our MVVM input/output. Technically those are not events. Yet, we are marking as EventProtocol to get for free MERLin sugar for enums. An input from a View is more correctly to be defined as an action. In that context, someone might find useful to update a state, instead of keep track of the current one with a variable and switch over it.

I repeat that I understand your point of view and you can see from the swift evolution pitch that this is also mine. But in a broader context what we think is possibly not necessarily true. There are use cases. one is the example I reported in my previous answer.

**Comment by classic-chris** [comment]
Giuseppe, I understand completely that it is syntactic sugar around what you show in your example. I don't personally like it as I believe this syntax is far more opaque than explicitly reassigning the value of the variable. I also don't believe it adds value to MERLin.

Approved nonetheless but I do think MERLin shouldn't try to please everyone all the time; we should stay focused on what provides value and avoid what may actually encourage poor code.

**Review by classic-chris — APPROVED** [review]

**Review by fabfelici — APPROVED** [review]

**Comment by gringoireDM** [comment]
I thought about it more than a little, and ultimately I decided that @classic-chris is right. Beside the fact that probably these features might be beneficial to MERLin users these are not MERLin primary goal. I've created a separate project for enums handling https://github.com/gringoireDM/EnumKit

We can decide on the slack channel if MERLin should be dependent from this package, or not.

**Pull request closed without merging**
